---
title: "STAT6101Project"
output: pdf_document
date: "2024-11-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# STAT6101 Final Project

## Uniform Case

```{r}

# generate the uniform probabilities
p_unif <- sort(runif(1000, min = 0, max = 1))

# budget is allowed budget, method is the type of shifting
# allowed method types: 
  # shifting as many people to 1 as much as the budget allows
  # shifting everyone an equal amount
  # shifting a section of people in the middle to a certain threshold...?
shift_probs <- function(probs, budget, method) {
  
  if (method == "max") {
    
    i = length(probs);
    while (budget >= (1 - probs[i])^2) {
      budget = budget - (1 - probs[i])^2
      probs[i] = 1
      i = i - 1
    }
    
  } else if (method == "uniform") {
    n <- length(probs)
    add_prob <- sqrt(budget / n)
    
    probs = pmin(probs + add_prob, 1)
  }
  
  return(probs)
}

```

shifting people away from 0
shifting one mode further vs the other
shifting people depending on their existing position
  eg linear
  quadratic probabilities makes shifting higher probabilities more make more sense

```{r}

beta_mix <- c(rbeta(500, 10, 30), 1 - rbeta(500, 10, 30))
hist(beta_mix, breaks = 50)

# cost function: x(y - x)^2, x|y - x|, ((x - 0.5)(y - x))^2, |x - 0.5|(y - x)^2

shift_probs <- function(probs, budget, method) {
  
  probs <- sort(probs)
  
  i = length(probs)
  while (budget > ((probs[i])(1 - probs[i]))^2) {
    budget = budget - ((probs[i])(1 - probs[i]))^2
    probs[i] = 1
    i = i - 1
  }
  
  return(probs)
}

```
uniform with cost x^2t^2

```{r}

shift_probs_max <- function(probs, budget, method) {
  
  probs <- sort(probs)
  
  i = length(probs)
  while (budget > ((probs[i])(1 - probs[i]))^2) {
    budget = budget - ((probs[i])(1 - probs[i]))^2
    probs[i] = 1
    i = i - 1
  }
  
  return(probs)
}

shift_probs_mid <- function(probs, budget, threshold) {
  
  probs <- sort(probs)
  
  i = floor(length(probs) / 2)
  while (budget > ((probs[i])(1 - probs[i]))^2) {
    budget = budget - ((probs[i])(1 - probs[i]))^2
    probs[i] = 1
    i = i - 1
  }
  
  return(probs)
}



```

```{r}

shift_probs_thresh <- function(probs, budget, threshold) {
  
  probs <- sort(probs)
  
  i = length(probs)
  
  for (j in 1:length(probs)) {
    if (probs[j] > threshold) {
      i = j - 1
      break
    }
  }
  
  while (budget > ((probs[i]) * (threshold - probs[i]))^2) {
    budget <- budget - ((probs[i]) * (threshold - probs[i]))^2
    probs[i] = threshold
    i = i - 1
    if (i == 0) {
      break
    }
  }
  
  return(probs)
}

probs <- shift_probs_thresh(data, 10, 1)

optimize <- seq(0.1, 1, 0.01)
vals <- rep(0, length(optimize))

for (i in 1:length(optimize)) {
  data <- runif(1000, min = 0, max = 1)
  
  probs_i <- shift_probs_thresh(data, 10, optimize[i])
  vals[i] <- sum(probs_i)
}

plot(cbind(optimize, vals))
```


